"""Generate the native searchable language catalog; --check rejects stale output."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def quote(value):
    return '"' + value.replace('$', '$$').replace('"', '$\\"').replace('\n', '$\\n') + '"'


def generate():
    entries = json.loads((ROOT / 'installer/catalog.json').read_text(encoding='utf-8'))['languages']
    package = json.loads((ROOT / 'package.json').read_text(encoding='utf-8'))
    assert entries[0]['locale'] == 'en' and entries[0]['windowsId'] == 1033
    for key in ('locale', 'windowsId', 'name'):
        assert len({entry[key] for entry in entries}) == len(entries), key
    assert [entry['installerCode'] for entry in entries] == package['build']['nsis']['installerLanguages']
    lines = ['; Generated by scripts/build_installer_catalog.py. Edit catalog.json.',
             '!macro RacallEachLanguage ACTION']
    for entry in entries:
        assert (ROOT / 'apps/shared/locales' / (entry['locale'] + '.json')).exists()
        assert entry['text'].keys() == entries[0]['text'].keys()
        lines.append('  !insertmacro ${ACTION} ' + ' '.join(quote(str(v)) for v in
            (entry['locale'], entry['windowsId'], entry['name'], ' '.join(entry['search']))))
    lines.append('!macroend')
    for entry in entries:
        for key, value in entry['text'].items():
            lines.append(f'LangString Racall_{key} {entry["windowsId"]} {quote(value)}')
    lines.append('!macro RacallLoadLanguages')
    lines.extend('  !insertmacro MUI_LANGUAGE ' + quote(entry['nsisLanguage']) for entry in entries)
    lines.append('!macroend')
    lines.extend(['!macro RacallTextVariables'])
    lines.extend('  Var RacallText_' + key for key in entries[0]['text'])
    lines.extend(['!macroend', '!macro RacallLoadText'])
    for entry in entries:
        lines.append('  ${If} $LANGUAGE == ' + str(entry['windowsId']))
        for key, value in entry['text'].items():
            lines.append('    StrCpy $RacallText_' + key + ' ' + quote(value))
        lines.append('  ${EndIf}')
    lines.append('!macroend')
    return '\n'.join(lines) + '\n' 


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    output = ROOT / 'installer/catalog.nsh'
    content = generate()
    if args.check:
        assert output.read_text(encoding='utf-8-sig') == content, 'Regenerate installer/catalog.nsh'
    else:
        output.write_text(content, encoding='utf-8-sig')
    print('Installer catalog: English default; catalog and application languages agree.')


if __name__ == '__main__':
    main()
