; Generated by scripts/build_installer_catalog.py. Edit catalog.json.
!macro RacallEachLanguage ACTION
  !insertmacro ${ACTION} "en" "1033" "English" "English en английский"
  !insertmacro ${ACTION} "ru" "1049" "Русский" "Русский ru Russian"
!macroend
LangString Racall_intro 1033 "Your sources, connected notes and AI research in one place."
LangString Racall_language 1033 "Choose your installation language"
LangString Racall_search 1033 "Search languages…"
LangString Racall_empty 1033 "No matching languages"
LangString Racall_choose 1033 "Select a language from the list."
LangString Racall_folder 1033 "Change folder…"
LangString Racall_required 1033 "Required:"
LangString Racall_available 1033 "Available:"
LangString Racall_unavailable 1033 "Free space unavailable"
LangString Racall_spaceError 1033 "There is not enough free space on the selected drive."
LangString Racall_folderTitle 1033 "Choose the parent folder for Racall"
LangString Racall_setup 1033 "Racall Setup"
LangString Racall_install 1033 "Install"
LangString Racall_cancel 1033 "Cancel"
LangString Racall_seedError 1033 "Could not save the installation language. Check access to the app folder."
LangString Racall_intro 1049 "Источники, связанные заметки и исследования с ИИ в одном месте."
LangString Racall_language 1049 "Выберите язык установки"
LangString Racall_search 1049 "Найти язык…"
LangString Racall_empty 1049 "Язык не найден"
LangString Racall_choose 1049 "Выберите язык из списка."
LangString Racall_folder 1049 "Изменить папку…"
LangString Racall_required 1049 "Требуется:"
LangString Racall_available 1049 "Свободно:"
LangString Racall_unavailable 1049 "Свободное место недоступно"
LangString Racall_spaceError 1049 "На выбранном диске недостаточно свободного места."
LangString Racall_folderTitle 1049 "Выберите папку для установки Racall"
LangString Racall_setup 1049 "Установка Racall"
LangString Racall_install 1049 "Установить"
LangString Racall_cancel 1049 "Отмена"
LangString Racall_seedError 1049 "Не удалось сохранить язык установки. Проверьте доступ к папке приложения."
!macro RacallLoadLanguages
  !insertmacro MUI_LANGUAGE "English"
  !insertmacro MUI_LANGUAGE "Russian"
!macroend
!macro RacallTextVariables
  Var RacallText_intro
  Var RacallText_language
  Var RacallText_search
  Var RacallText_empty
  Var RacallText_choose
  Var RacallText_folder
  Var RacallText_required
  Var RacallText_available
  Var RacallText_unavailable
  Var RacallText_spaceError
  Var RacallText_folderTitle
  Var RacallText_setup
  Var RacallText_install
  Var RacallText_cancel
  Var RacallText_seedError
!macroend
!macro RacallLoadText
  ${If} $LANGUAGE == 1033
    StrCpy $RacallText_intro "Your sources, connected notes and AI research in one place."
    StrCpy $RacallText_language "Choose your installation language"
    StrCpy $RacallText_search "Search languages…"
    StrCpy $RacallText_empty "No matching languages"
    StrCpy $RacallText_choose "Select a language from the list."
    StrCpy $RacallText_folder "Change folder…"
    StrCpy $RacallText_required "Required:"
    StrCpy $RacallText_available "Available:"
    StrCpy $RacallText_unavailable "Free space unavailable"
    StrCpy $RacallText_spaceError "There is not enough free space on the selected drive."
    StrCpy $RacallText_folderTitle "Choose the parent folder for Racall"
    StrCpy $RacallText_setup "Racall Setup"
    StrCpy $RacallText_install "Install"
    StrCpy $RacallText_cancel "Cancel"
    StrCpy $RacallText_seedError "Could not save the installation language. Check access to the app folder."
  ${EndIf}
  ${If} $LANGUAGE == 1049
    StrCpy $RacallText_intro "Источники, связанные заметки и исследования с ИИ в одном месте."
    StrCpy $RacallText_language "Выберите язык установки"
    StrCpy $RacallText_search "Найти язык…"
    StrCpy $RacallText_empty "Язык не найден"
    StrCpy $RacallText_choose "Выберите язык из списка."
    StrCpy $RacallText_folder "Изменить папку…"
    StrCpy $RacallText_required "Требуется:"
    StrCpy $RacallText_available "Свободно:"
    StrCpy $RacallText_unavailable "Свободное место недоступно"
    StrCpy $RacallText_spaceError "На выбранном диске недостаточно свободного места."
    StrCpy $RacallText_folderTitle "Выберите папку для установки Racall"
    StrCpy $RacallText_setup "Установка Racall"
    StrCpy $RacallText_install "Установить"
    StrCpy $RacallText_cancel "Отмена"
    StrCpy $RacallText_seedError "Не удалось сохранить язык установки. Проверьте доступ к папке приложения."
  ${EndIf}
!macroend
